apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: etcd-ingress
  namespace: sensugo
  annotations:
    kubernetes.io/ingress.class: private-nginx
spec:
  rules:
  - host: sensugo-prod-etcd.mediaiqdigital.com
    http:
      paths:
      - backend:
          serviceName: etcd-client
          servicePort: 2379
        path: /
