## ####
## Create Secrets - for admin and write-user and grafana read-only passwords
## kubectl create secret generic write-user --from-literal=write-user-password='********' -n influxdb
## kubectl create secret generic admin-user --from-literal=admin-password='********' -n influxdb
## kubectl create secret generic grafana-user --from-literal=grafana-password='********' -n influxdb
## ####
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: influxdb
spec:
  serviceName: influxdb-svc
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-config
        configMap:
          defaultMode: 420
          name: influxdb-config
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-data-pvc
      containers:
      - image: influxdb:latest
        imagePullPolicy: Always
        name: influxdb
        ports:
          - protocol: TCP
            containerPort: 8082
          - protocol: TCP
            containerPort: 8086
          - protocol: UDP
            containerPort: 8089
          - protocol: TCP
            containerPort: 8093
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: INFLUXDB_ADMIN_USER
            value: "admin"
          - name: INFLUXDB_WRITE_USER
            value: "sensugo"
          - name: INFLUXDB_DB
            value: metrics
          - name: INFLUXDB_GRAPHITE_ENABLED
            value: "true"
          - name: INFLUXDB_READ_USER
            value: grafana
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: admin-password
          - name: INFLUXDB_WRITE_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: write-user
                key: write-user-password
          - name: INFLUXDB_READ_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-user
                key: grafana-password
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
        volumeMounts:
        - mountPath: /etc/influxdb/influxdb.conf
          name: influxdb-config
          subPath: influxdb.conf
        - mountPath: /var/lib/influxdb/
          name: influxdb-data
      nodeSelector:
        app: sensugo
      tolerations:
        - effect: NoExecute
          key: app
          operator: Equal
          value: sensugo
  volumeClaimTemplates:
  - metadata:
      name: influxdb-data
    spec:
      storageClassName: performance-retain
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: influxdb
spec:
  clusterIP: None
  selector:
    app: influxdb
  ports:
    - name: flux
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: api
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: udp
      protocol: UDP
      port: 8089
      targetPort: 8089
    - name: fluxd
      protocol: TCP
      port: 8093
      targetPort: 8093
