apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensugo-ingress
  namespace: sensugo
spec:
  rules:
  - host: sensugo-backend.example.com
    http:
      paths:
      - backend:
          serviceName: sensu-backend
          servicePort: 8080
  - host: sensu-dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: sensu-backend
          servicePort: 3000
