type: CheckConfig
api_version: core/v2
metadata:
  name: jarvis-get-elements
  namespace: jarvis
spec:
  command: jarvis-total-elements.py
  handlers:
  - slack
  - influxdb
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: graphite_plaintext
  output_metric_handlers:
  - influxdb
  publish: true
  round_robin: true
  runtime_assets:
  - sensu-plugins-http
  - jarvis-plugins
  subscriptions:
  - jarvis
  timeout: 0
  ttl: 0
