type: CheckConfig
api_version: core/v2
metadata:
  name: sample-python-check
  namespace: devops
spec:
  check_hooks: null
  command: py_sensu.py
  env_vars: null
  handlers:
  - influxdb
  high_flap_threshold: 0
  interval: 60
  low_flap_threshold: 0
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
  proxy_entity_name: ""
  publish: true
  round_robin: true
  runtime_assets:
  - python-sample
  stdin: false
  subdue: null
  subscriptions:
  - devops
  timeout: 0
  ttl: 0
