apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensugo-ingress
  namespace: sensugo
spec:
  rules:
  - host: sensugo-grafana.example.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3001
