api_version: core/v2
type: Handler
metadata:
  namespace: devops
  name: slack
spec:
  type: pipe
  runtime_assets:
  - slack-handler
  command: sensu-slack-handler --channel '#sensugo-demo' --timeout 20 --username 'sensu' --webhook-url 'https://hooks.slack.com/services/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' 
  timeout: 30
  filters:
  - is_incident
  - not_silenced
